-- Execute este SQL no Supabase SQL Editor antes de publicar a aplicação.
-- Para maior privacidade em uma próxima versão, migre a consulta de posição
-- para uma RPC ou Edge Function e restrinja o SELECT direto da tabela.

create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text not null unique,
  goal text not null,
  status text not null default 'waiting',
  created_at timestamptz not null default now(),
  constraint waitlist_status_check check (status in ('waiting', 'called')),
  constraint waitlist_goal_check check (
    goal in (
      'Emagrecimento',
      'Cirurgia Bariátrica',
      'Saúde intestinal',
      'Medicina de precisão',
      'Nutrição clínica',
      'Hipertrofia'
    )
  )
);

create index if not exists waitlist_phone_idx on public.waitlist (phone);
create index if not exists waitlist_status_idx on public.waitlist (status);
create index if not exists waitlist_status_id_idx on public.waitlist (status, id);

alter table public.waitlist enable row level security;

drop policy if exists "Public can join waitlist" on public.waitlist;
create policy "Public can join waitlist"
on public.waitlist
for insert
to anon
with check (status = 'waiting');

drop policy if exists "Public can consult waitlist" on public.waitlist;
create policy "Public can consult waitlist"
on public.waitlist
for select
to anon
using (true);
